### ISSUE TITLE
Strange bug, plug-in has to close

### ISSUE THREAD

**Issue by sludgeFudge** [kamilburda/batcher#13]
#### What went wrong?

```
Traceback (most recent call last):
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/procedure.py", line 385, in func_wrapper
    return_values = func(*procedure_and_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/batcher.py", line 54, in plug_in_batch_export_layers
    return _run_interactive(
           ^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/batcher.py", line 215, in _run_interactive
    update_successful, message = _load_and_update_settings(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/batcher.py", line 257, in _load_and_update_settings
    status, load_message = update.load_and_update(settings, source_name=source_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/src/update.py", line 88, in load_and_update
    load_result = settings.load(sources, modify_data_func=_handle_update)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/group.py", line 585, in load
    return persistor_.Persistor.load([self], *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/persistor.py", line 154, in load
    settings_not_loaded, statuses_per_source, messages_per_source = cls._load(
                                                                    ^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/persistor.py", line 171, in _load
    source.read(settings_not_loaded, modify_data_func=modify_data_func)
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/sources.py", line 103, in read
    self._update_settings(settings_or_groups, processed_data)
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/sources.py", line 119, in _update_settings
    self._update_group(setting_or_group, setting_path, data_dict)
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/sources.py", line 178, in _update_group
    self._update_setting(matching_children[path], dict_)
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/sources.py", line 245, in _update_setting
    setting.set_value(setting_dict['value'])
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/setting/settings.py", line 443, in set_value
    value = self._raw_to_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/src/setting_classes.py", line 284, in _raw_to_value
    item_object = pg.pdbutils.get_item_from_image_and_item_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/pdbutils.py", line 160, in get_item_from_image_and_item_path
    item_path_components[0], _get_children_from_image(image, item_class_name))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/batcher/pygimplib/pdbutils.py", line 198, in _get_children_from_image
    raise TypeError(
TypeError: invalid item type "TextLayer"; must be Layer, Channel or Vectors

```

#### If you can, tell us the steps to reproduce the problem.

1. Just save your multilayered .xcf file
2. Then Export as Layers...

The weird thing is it worked all this while. Then today I got this bug, but I was able to export normally once. After that it wouldn't budge. I updated to the newer plug-in version but I'm still getting the same error.

#### Configuration

Version of Batcher: 0.4, July 13, 2024

Version of GIMP: 2.99.18

Operating system: Fedora 40 (Workstation) 

Flatpak beta

**Comment by sludgeFudge** [comment]
Sorry, my bad. It seems the old files were still around somewhere.

**Comment by kamilburda** [comment]
Actually, you did find a bug that I just fixed 🙂

The crash occurred when you selected a text layer in the plug-in preview, saved the settings, closed the plug-in, and ran the plug-in again.

So thanks for the find 😊
