### ISSUE TITLE
batcher crashed on export in snapped GIMP 2.99.16

### ISSUE THREAD

**Issue by Saviq** [kamilburda/batcher#8]
#### What went wrong?
```
Traceback (most recent call last):
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/pygimplib/procedure.py", line 373, in func_wrapper
    return_values = func(*procedure_and_args)
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/batcher.py", line 76, in plug_in_batch_export_layers_now
    return _run_export_layers_now_interactive(layer_tree)
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/batcher.py", line 170, in _run_export_layers_now_interactive
    gui_main.ExportLayersNowDialog(layer_tree, SETTINGS)
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/src/gui/main.py", line 1191, in __init__
    self.run_batcher()
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/src/gui/main.py", line 1235, in run_batcher
    self._batcher.run(
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/src/core.py", line 368, in run
    self._setup_contents()
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/src/core.py", line 866, in _setup_contents
    self._image_copy = pg.pdbutils.duplicate_image_without_contents(self._input_image)
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/pygimplib/pdbutils.py", line 37, in duplicate_image_without_contents
    pdb.gimp_image_set_unit(new_image, pdb.gimp_image_get_unit(image))
  File "/home/michal/snap/gimp/425/.config/GIMP/2.99/plug-ins/batcher/pygimplib/pypdb.py", line 121, in __call__
    result = self._proc.run(config)
TypeError: argument args: Expected Gimp.ValueArray, but got __gi__.GimpProcedureConfig-gimp-image-get-unit
```

#### If you can, tell us the steps to reproduce the problem.
```
$ snap install gimp --channel preview/stable
# install batcher in ~/snap/gimp/current/.config/GIMP/2.99/plug-ins
# try exporting layers
```

#### Configuration

Version of Batcher: 0.2

Version of GIMP:  2.99.16

Operating system: Ubuntu Noble Numbat (devel)

**Comment by kamilburda** [comment]
Hi, Batcher version 0.2 requires GIMP 2.99.18. The changes are backwards incompatible, so 0.2 will not work with GIMP 2.99.16.

I forgot to update the GitHub repository description to refer to GIMP 2.99.18, which is now fixed.
